name = "BitInformation"
uuid = "de688a37-743e-4ac2-a6f0-bd62414d1aa7"
authors = ["Milan <milankloewer@gmx.de> and contributors"]
version = "0.6.3"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
Distributions = "0.24, 0.25"
StatsBase = "0.32, 0.33, 0.34"
Random = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
